# Clippy Configuration
cognitive-complexity-threshold = 25
too-many-lines-threshold = 150
too-many-arguments-threshold = 7
type-complexity-threshold = 250
avoid-breaking-exported-api = true
allow-expect-in-tests = true
allow-unwrap-in-tests = true
msrv = "1.85.0"
